apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentd-application
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  source:
    chart: fluentd
    repoURL: https://fluent.github.io/helm-charts
    targetRevision: 0.5.2
    helm:
      parameters:
        - name: image.repository
          value: fluent/fluentd-kubernetes-daemonset
        - name: image.tag
          value: v1.18-debian-papertrail-1
        - name: resources.requests.cpu
          value: "10m"
        - name: resources.requests.memory
          value: 128Mi
        - name: resources.limits.memory
          value: 128Mi
        - name: autoscaling.enabled
          value: "true"
        - name: autoscaling.minReplicas
          value: "1"
        - name: autoscaling.maxReplicas
          value: "2"
        - name: autoscaling.targetCPUUtilizationPercentage
          value: "80"
        - name: serviceAccount.create
          value: "true"
        - name: serviceAccount.name
          value: fluentd-role
        - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
          value: arn:aws:iam::<YOUR_ACCOUNT_ID>:role/<YOUR_FLUENTD_ROLE>
        - name: plugins[0]
          value: fluent-plugin-grafana-loki
        - name: plugins[1]
          value: fluent-plugin-cloudwatch-logs
        - name: plugins[2]
          value: fluent-plugin-elasticsearch
        - name: fileConfigs.01_sources\.conf
          value: |
            ## logs from podman
            <source>
              @type tail
              @id in_tail_container_logs
              @label @KUBERNETES
              path /var/log/containers/*.log
              pos_file /var/log/fluentd-containers.log.pos
              tag kubernetes.*
              read_from_head true
              <parse>
                @type multi_format
                <pattern>
                  format json
                  time_key time
                  time_type string
                  time_format "%Y-%m-%dT%H:%M:%S.%NZ"
                  keep_time_key false
                </pattern>
                <pattern>
                  format regexp
                  expression /^(?<time>.+) (?<stream>stdout|stderr)( (.))? (?<log>.*)$/
                  time_format '%Y-%m-%dT%H:%M:%S.%NZ'
                  keep_time_key false
                </pattern>
              </parse>
              emit_unmatched_lines true
            </source>
            # expose metrics in prometheus format
            <source>
              @type prometheus
              bind 0.0.0.0
              port 24231
              metrics_path /metrics
            </source>
        - name: fileConfigs.02_filters\.conf
          value: |
            <label @KUBERNETES>
              <match kubernetes.var.log.containers.fluentd**>
                @type relabel
                @label @FLUENT_LOG
              </match>
              # <match kubernetes.var.log.containers.**_kube-system_**>
              #   @type null
              #   @id ignore_kube_system_logs
              # </match>
              <filter kubernetes.**>
                @type kubernetes_metadata
                @id filter_kube_metadata
                skip_labels false
                skip_container_metadata false
                skip_namespace_metadata true
                skip_master_url true
              </filter>
              <match **>
                @type relabel
                @label @DISPATCH
              </match>
            </label>
        - name: fileConfigs.03_dispatch\.conf
          value: |
            <label @DISPATCH>
              <filter **>
                @type prometheus
                <metric>
                  name fluentd_input_status_num_records_total
                  type counter
                  desc The total number of incoming records
                  <labels>
                    tag ${tag}
                    hostname ${hostname}
                  </labels>
                </metric>
              </filter>
              <match **>
                @type relabel
                @label @OUTPUT
              </match>
            </label>
        - name: fileConfigs.04_outputs\.conf
          value: |
            <label @OUTPUT>
              <match **>
                @type elasticsearch
                host "elasticsearch-master"
                port 9200
                path ""
                user elastic
                password changeme
                # Don't wait for elastic to start up.
                verify_es_version_at_startup false
              </match>
            </label>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
