apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentd-application
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  source:
    chart: fluentd
    repoURL: https://fluent.github.io/helm-charts
    targetRevision: 0.5.2
    helm:
      parameters:
        - name: image.repository
          value: fluent/fluentd-kubernetes-daemonset
        - name: image.tag
          value: v1.18-debian-cloudwatch-1
        - name: resources.requests.cpu
          value: "10m"
        - name: resources.requests.memory
          value: 128Mi
        - name: resources.limits.memory
          value: 128Mi
        - name: autoscaling.enabled
          value: "true"
        - name: autoscaling.minReplicas
          value: "1"
        - name: autoscaling.maxReplicas
          value: "2"
        - name: autoscaling.targetCPUUtilizationPercentage
          value: "80"
        - name: serviceAccount.create
          value: "true"
        - name: serviceAccount.name
          value: fluentd-role
        - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
          value: arn:aws:iam::<YOUR_ACCOUNT_ID>:role/<YOUR_FLUENTD_ROLE>
        - name: plugins[0]
          value: fluent-plugin-grafana-loki
        - name: plugins[1]
          value: fluent-plugin-cloudwatch-logs
        - name: plugins[2]
          value: fluent-plugin-prometheus
        - name: metrics.enabled
          value: "true"
        - name: metrics.port
          value: "24231"

        # Lifehack starts here: blank the default config files
        - name: fileConfigs.01_sources.conf
          value: ""
        - name: fileConfigs.02_filters.conf
          value: ""
        - name: fileConfigs.03_dispatch.conf
          value: ""
        - name: fileConfigs.04_outputs.conf
          value: ""

        # Main config file instead of the split ones
        - name: fileConfigs.main.conf
          value: |
            <source>
              @type cloudwatch_logs
              region eu-west-1
              log_group_name awie-g3-d-kta-app-01-log
              log_stream_name i-0ba38e333685bfdb9
              aws_sts_role_arn arn:aws:iam::727594547879:role/awie-iamr-ngdev-api-fluentd
              tag cloudwatch.app
              <parse>
                @type json
              </parse>
            </source>

            <source>
              @type cloudwatch_logs
              region eu-west-1
              log_group_name i-0634db85aa69ded3d
              log_stream_name trans-log-stream
              aws_sts_role_arn arn:aws:iam::727594547879:role/awie-iamr-ngdev-api-fluentd
              tag cloudwatch.trans
              <parse>
                @type json
              </parse>
            </source>

            <source>
              @type prometheus
              port 24224
              bind 0.0.0.0
            </source>

            <source>
              @type prometheus_monitor
              <labels>
                host ${hostname}
              </labels>
            </source>

            <source>
              @type prometheus_output_monitor
              <labels>
                host ${hostname}
              </labels>
            </source>

            <label @OUTPUT>
              <match cloudwatch.app>
                @type loki
                url http://loki-query-frontend:3100
                <label>
                  app fluentd
                  name awie-g3-d-kta-app-01-log
                  namespace monitoring
                </label>
                <buffer>
                  @type file
                  @id buffer_cloudwatch_app
                  path /fluentd/buffer/cloudwatch_app
                  total_limit_size 1g
                  chunk_limit_size 50m
                  flush_interval 5s
                  flush_at_shutdown true
                  queue_limit_length 32
                  retry_forever true
                  overflow_action drop_oldest_chunk
                  persistent true
                </buffer>
              </match>

              <match cloudwatch.trans>
                @type loki
                url http://loki-query-frontend:3100
                <label>
                  app fluentd
                  name awie-g3-d-kta-trans-01-log
                  namespace monitoring
                </label>
                <buffer>
                  @type file
                  @id buffer_cloudwatch_trans
                  path /fluentd/buffer/cloudwatch_trans
                  total_limit_size 1g
                  chunk_limit_size 50m
                  flush_interval 5s
                  flush_at_shutdown true
                  queue_limit_length 32
                  retry_forever true
                  overflow_action drop_oldest_chunk
                  persistent true
                </buffer>
              </match>
            </label>

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true

