apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-azure-keyvault-secret
spec:
  provider: azure
  secretStoreName: my-keyvault
  secretObjects:
    - secretName: my-secret
      objectType: secret
      data:
        - objectName: secretKey1
          key: username
        - objectName: secretKey2
          key: password
  providerConfig:
    keyvaultName: "your-keyvault-name"
    tenantId: "your-tenant-id"
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    objects: |
      array:
        - |
          objectName: secretKey1
          objectType: secret
          objectVersion: ""
        - |
          objectName: secretKey2
          objectType: secret
          objectVersion: ""
  rotation: true
  rotationInterval: "5"
